name: tripnest
description: TripNest mobile app UI
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.7
  path_provider: ^2.1.2
  path: ^1.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
